import { Router } from 'express';
import mongoose from 'mongoose';
import { createHash, randomUUID } from 'node:crypto';
import { Command } from '@langchain/langgraph';
import mammoth from 'mammoth';
import JSZip from 'jszip';
import Application from '../models/Application.js';
import MasterResume from '../models/MasterResume.js';
import ResumeBullet from '../models/ResumeBullet.js';
import { normalizeSkills } from '../services/normalizeSkills.js';
import { canonicalizeSkill } from '../services/canonicalizeSkill.js';
import { tagBullet } from '../services/tagBullet.js';
import { verifyBullet, verifySummary, trustHumanEdit } from '../services/deterministicVerification.js';
import { gapAnalysis } from '../services/gapAnalysis.js';
import { computeVerifiedSkills } from '../services/verifiedSkills.js';
import { computeSkillFrequency } from '../services/skillFrequency.js';
import { findUnsupportedSeniorityTerms } from '../services/suggestResumeTitle.js';
import { atsScoreAndRecruiter } from '../services/atsScoreAndRecruiter.js';
import { buildResumeDocxBuffer } from '../services/exportResumeDocx.js';
import { buildCoverLetterDocxBuffer } from '../services/exportCoverLetterDocx.js';
import { buildTrackerXlsxBuffer } from '../services/exportTrackerXlsx.js';
import { convertDocxBufferToPdf } from '../services/convertDocxToPdf.js';
import { buildExportFilename } from '../services/buildExportFilename.js';
import { getJobAgentGraph, getCheckpointer } from '../graph/graphInstance.js';
import GenerationCache from '../models/GenerationCache.js';
import { authenticate } from '../middleware/authenticate.js';
import { getSkillDictionaryForUser } from '../services/skillAliasesStore.js';

const router = Router();
router.use(authenticate);

// LangGraph's default recursionLimit is 25 super-steps. A single pass that
// legitimately uses all 3 automatic retries (section 5) costs 9 + 3×6 = 27
// steps with a cover letter requested (coverLetterGeneration adds one node
// per cycle), or 8 + 3×5 = 23 without one — so the documented, correctly-
// enforced retry cap could still blow past the default limit and crash with
// an uncaught GraphRecursionError before ever reaching node 10. Raised with
// headroom rather than tuned to the exact worst case, since a manual retry
// or an accepted skill suggestion (also routed through this same invoke)
// can itself trigger further automatic retries on top.
const GRAPH_RECURSION_LIMIT = 60;

// Section 5 — "Cap retries at 3 regardless of reason," shared across
// automatic retries (enforced inside shouldRetryAutomatically) and manual
// ones. A manual "send back with notes" or an accepted suggest-missing-
// skills bullet both route through the same POST-triggered retry pathway
// (section 4a) but never went through the automatic loop's own cap check,
// so retryCount could otherwise climb past 3 indefinitely — checked here,
// before either route ever invokes the graph, so a refused retry costs
// nothing (no LLM call, no DB write).
const MAX_RETRY_COUNT = 3;

function buildResumeBulletsForGraph(bullets) {
  return bullets.map((bullet) => ({
    bulletId: bullet._id.toString(),
    text: bullet.text,
    role: bullet.role,
    company: bullet.company,
    dateRange: bullet.dateRange,
    canonicalSkills: bullet.canonicalSkills,
  }));
}

// A short, human-recognizable stand-in for a bullet in a flag message — never
// its internal id, which means nothing to whoever's reading the flag.
function truncateForFlag(text, maxLength = 50) {
  if (!text) return '';
  return text.length > maxLength ? `${text.slice(0, maxLength).trimEnd()}…` : text;
}

// Display-only, never persisted — same "compute live, don't store" pattern
// as verifiedSkills/skillMatchTypes. Only meaningful for a hand-edited title,
// since the AI suggestion can never contain one of these words by construction.
function computeTitleSeniorityWarning(tailoredTitle) {
  if (tailoredTitle?.editSource !== 'human') return [];
  return findUnsupportedSeniorityTerms(tailoredTitle.finalText);
}

// Resumes the one interrupt() in node 10 with a Command, then reads back the
// resulting checkpoint — the only place this route file touches the graph.
async function resumeGraph(applicationId, resumePayload) {
  const graph = getJobAgentGraph();
  await graph.invoke(new Command({ resume: resumePayload }), {
    configurable: { thread_id: applicationId },
    recursionLimit: GRAPH_RECURSION_LIMIT,
  });
  return graph.getState({ configurable: { thread_id: applicationId } });
}

// Section 4a — re-check computation. Runs node 6 AND node 9 against an
// application's CURRENT tailoredBullets/tailoredSummary (possibly hand-edited,
// or freshly regenerated by a retry), without saving. Shared by the standalone
// POST /:id/recheck route and by the retry branch of POST /:id/resume, so the
// human-recheck panel reflects a fresh retry immediately instead of only
// updating on the next manual "Re-check edited text" click.
async function computeHumanRecheck(application) {
  const graph = getJobAgentGraph();
  const snapshot = await graph.getState({ configurable: { thread_id: application._id.toString() } });
  const { resumeBullets = [], matchedSkills = [], yearsOfExperience, resumeTitle } = snapshot.values || {};
  const bulletsById = new Map(resumeBullets.map((bullet) => [bullet.bulletId, bullet]));
  const { aliases, matchers } = await getSkillDictionaryForUser(application.userId.toString());

  const bulletResults = application.tailoredBullets.map((tailoredBullet) => {
    const sourceBullet = bulletsById.get(tailoredBullet.sourceBulletId);
    const result =
      tailoredBullet.editSource === 'human'
        ? trustHumanEdit(tailoredBullet.finalText, matchers, aliases)
        : verifyBullet({ generatedText: tailoredBullet.finalText, sourceBullet }, matchers, aliases);
    return { bulletId: tailoredBullet.bulletId, rejected: tailoredBullet.rejected, finalText: tailoredBullet.finalText, ...result };
  });
  const bulletFlags = bulletResults.flatMap((result) => {
    const label = truncateForFlag(result.finalText);
    return [
      ...result.fabricatedSkills.map((skill) => `Bullet "${label}": fabricated skill "${skill}"`),
      ...result.fabricatedMetrics.map((metric) => `Bullet "${label}": fabricated metric "${metric}"`),
    ];
  });

  const selectedBullets = application.tailoredBullets
    .filter((tailoredBullet) => !tailoredBullet.rejected)
    .map((tailoredBullet) => bulletsById.get(tailoredBullet.sourceBulletId));
  const summaryResult = !application.tailoredSummary
    ? { passed: true, fabricatedSkills: [], fabricatedMetrics: [], claimedSkills: [] }
    : application.tailoredSummary.editSource === 'human'
      ? trustHumanEdit(application.tailoredSummary.finalText, matchers, aliases)
      : verifySummary(
          {
            generatedText: application.tailoredSummary.finalText,
            matchedSkills,
            selectedBullets,
            yearsOfExperience,
          },
          matchers,
          aliases
        );

  const summaryFlags = [
    ...summaryResult.fabricatedSkills.map((skill) => `Summary: fabricated skill "${skill}"`),
    ...summaryResult.fabricatedMetrics.map((metric) => `Summary: fabricated metric "${metric}"`),
  ];

  const overallPassed = bulletResults.every((result) => result.passed) && summaryResult.passed;

  // A live view of what's actually missing from the file you're about to
  // download — deliberately NOT unioned with the master resume's permanent
  // skill tags. Those tags describe your resume as a whole, not this specific
  // tailored output; a skill can be permanently tagged on some other bullet
  // while being completely absent from every bullet that's actually part of
  // this application (rejected, or edited to remove it) — in that case the
  // exported file genuinely doesn't cover it, and this list must say so.
  // Never overwrites the original keywordGaps, which stays tied to the master
  // resume for the separate "worth adding a permanent bullet" decision.
  const verifiedBulletSkills = bulletResults
    .filter((result) => !result.rejected)
    .flatMap((result) => result.claimedSkills.filter((skill) => !result.fabricatedSkills.includes(skill)));
  const verifiedSummarySkills = summaryResult.claimedSkills.filter((skill) => !summaryResult.fabricatedSkills.includes(skill));
  const effectiveSkills = [...new Set([...verifiedBulletSkills, ...verifiedSummarySkills])];
  const humanRecheckKeywordGaps = gapAnalysis(application.jdCanonicalSkills, effectiveSkills);

  const atsResult = await atsScoreAndRecruiter({
    jdText: application.jdSnapshot,
    tailoredBullets: application.tailoredBullets.filter((bullet) => !bullet.rejected),
    tailoredSummary: application.tailoredSummary,
    resumeTitle: application.tailoredTitle?.finalText || resumeTitle,
    coverLetterText: application.coverLetterText,
    keywordGaps: humanRecheckKeywordGaps,
    verificationResult: { bullets: bulletResults, summary: summaryResult, overallPassed },
    applicationId: application._id.toString(),
    resumeVersion: application.masterResumeId,
  });

  return {
    humanRecheckAtsScore: atsResult.atsScore,
    // No prefix on these — same bare enum values (e.g. "missingRequirement") as
    // the original AI pass's atsFlags, so the two never look like different
    // kinds of thing when the UI swaps between them in the same slot.
    humanRecheckAtsFlags: [...bulletFlags, ...summaryFlags, ...atsResult.atsFlags],
    humanRecheckRecruiterFeedback: atsResult.recruiterFeedback,
    humanRecheckKeywordGaps,
  };
}

// For the Applications list page — every application, most recently active first.
router.get('/', async (req, res) => {
  try {
    const applications = await Application.find({ userId: req.user.id }).sort({ updatedAt: -1 });
    return res.json({ applications });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to list applications.' });
  }
});

// A real job posting is a few KB at most. This exists to fail fast with a
// clear message instead of letting an absurdly large paste reach the JD-
// keyword-extraction LLM call, where it can blow past the provider's
// per-minute token limit and throw from deep inside the graph.
const MAX_JD_LENGTH = 20000;

// Section 3 — create + start.
router.post('/', async (req, res) => {
  const { masterResumeId, jdText, companyName, jobTitle, referenceUrl, coverLetterRequested } = req.body;

  if (!mongoose.isValidObjectId(masterResumeId)) {
    return res.status(400).json({ error: 'Invalid masterResumeId.' });
  }
  if (typeof jdText !== 'string' || !jdText.trim()) {
    return res.status(400).json({ error: 'jdText is required.' });
  }
  if (jdText.length > MAX_JD_LENGTH) {
    return res.status(400).json({ error: `jdText is too long (max ${MAX_JD_LENGTH} characters).` });
  }
  if (typeof companyName !== 'string' || !companyName.trim()) {
    return res.status(400).json({ error: 'companyName is required.' });
  }
  if (typeof jobTitle !== 'string' || !jobTitle.trim()) {
    return res.status(400).json({ error: 'jobTitle is required.' });
  }

  try {
    const normalizedJdText = jdText.trim().replace(/\s+/g, ' ');
    const jdTextHash = createHash('sha256').update(normalizedJdText).digest('hex');

    const existing = await Application.findOne({ masterResumeId, jdTextHash, userId: req.user.id });
    if (existing) {
      return res.json({ application: existing, deduped: true });
    }

    const resume = await MasterResume.findOne({ _id: masterResumeId, status: 'active', userId: req.user.id });
    if (!resume) {
      return res.status(404).json({ error: 'Resume not found.' });
    }

    const bullets = await ResumeBullet.find({ masterResumeId }).sort({ order: 1 });
    if (bullets.length === 0) {
      return res.status(400).json({ error: 'Selected resume has no bullets.' });
    }

    const { aliases: skillAliases } = await getSkillDictionaryForUser(req.user.id);
    const resumeCanonicalSkills = normalizeSkills(bullets.flatMap((bullet) => bullet.skills), skillAliases);
    const resumeBulletsForGraph = buildResumeBulletsForGraph(bullets);
    const projectCanonicalSkills = normalizeSkills(
      (resume.projects || []).flatMap((project) => project.canonicalSkills || []),
      skillAliases
    );

    let application;
    try {
      application = await Application.create({
        userId: req.user.id,
        masterResumeId,
        companyName: companyName.trim(),
        jobTitle: jobTitle.trim(),
        referenceUrl: (referenceUrl || '').trim(),
        jdSnapshot: jdText,
        jdTextHash,
        coverLetterRequested: Boolean(coverLetterRequested),
        status: 'in_progress',
        // A resume that predates `timestamps: true` has no updatedAt of its
        // own yet on this first read — uploadedAt is the honest fallback.
        masterResumeSnapshotAt: resume.updatedAt || resume.uploadedAt,
      });
    } catch (err) {
      if (err.code === 11000) {
        const winner = await Application.findOne({ masterResumeId, jdTextHash, userId: req.user.id });
        return res.json({ application: winner, deduped: true });
      }
      throw err;
    }

    const applicationId = application._id.toString();
    const graph = getJobAgentGraph();

    // Everything from here on can throw mid-flight (an LLM provider rate
    // limit or outage, a graph error) after the application row above already
    // exists. Without this guard a thrown error left that row stranded at
    // status 'in_progress' forever — invisible in the UI, no error recorded,
    // no way to retry. On any failure past this point, undo the create
    // instead of leaving a row nothing can ever resolve.
    try {
      await graph.invoke(
        {
          applicationId,
          userId: req.user.id,
          masterResumeId,
          companyName: companyName.trim(),
          jdText,
          jdTitle: jobTitle.trim(),
          resumeSummary: resume.summary,
          resumeTitle: resume.personalInfo?.title,
          resumeCanonicalSkills,
          resumeBullets: resumeBulletsForGraph,
          projectCanonicalSkills,
          // Frozen, display-only snapshots — see jobAgentGraph.js.
          resumeProjects: resume.projects || [],
          resumeEducation: resume.education || [],
          resumeCertifications: resume.certifications || [],
          resumeVolunteerWork: resume.volunteerWork || [],
          coverLetterRequested: Boolean(coverLetterRequested),
        },
        { configurable: { thread_id: applicationId }, recursionLimit: GRAPH_RECURSION_LIMIT }
      );

      const snapshot = await graph.getState({ configurable: { thread_id: applicationId } });
      const state = snapshot.values;

      application.jdKeywords = state.jdKeywords;
      application.jdCanonicalSkills = state.jdCanonicalSkills;
      application.keywordGaps = state.keywordGaps;

      if (state.roleFit?.fit === 'low') {
        application.status = 'role_mismatch';
      } else {
        application.status = 'pending_approval';
        application.tailoredBullets = state.tailoredBullets;
        application.tailoredSummary = state.tailoredSummary;
        application.tailoredTitle = state.tailoredTitle;
        application.coverLetterText = state.coverLetterText;
        application.atsScore = state.atsScore;
        application.atsFlags = state.atsFlags;
        application.recruiterFeedback = state.recruiterFeedback;
        application.retryCount = state.retryCount ?? 0;
      }

      await application.save();
    } catch (err) {
      await Application.deleteOne({ _id: applicationId });
      const checkpointer = getCheckpointer();
      await checkpointer.deleteThread(applicationId);
      await GenerationCache.deleteMany({ applicationId });
      throw err;
    }

    return res.status(201).json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to create and start application.' });
  }
});

// For the Approval page — merges the Mongo doc with data section 8 doesn't
// persist (the original bullets, the verification result, the role-mismatch
// reason), sourced live from the checkpointer instead of duplicating it.
router.get('/:id', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    const graph = getJobAgentGraph();
    const snapshot = await graph.getState({ configurable: { thread_id: id } });
    const state = snapshot.values || {};

    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id }).select(
      'skills projects education certifications volunteerWork updatedAt'
    );

    // Frozen-at-creation snapshot, falling back to a live read only for an
    // application from before these fields existed (state.x is undefined
    // there, never merely empty) — see jobAgentGraph.js.
    const originalProjects = state.resumeProjects ?? resume?.projects ?? [];
    const originalEducation = state.resumeEducation ?? resume?.education ?? [];
    const originalCertifications = state.resumeCertifications ?? resume?.certifications ?? [];
    const originalVolunteerWork = state.resumeVolunteerWork ?? resume?.volunteerWork ?? [];

    // Verified-skills is display-only (see verifiedSkills.js) — scoped to what
    // this specific application will actually export: non-rejected tailored
    // bullets' current text, plus the (frozen) Projects section, which
    // the export always includes verbatim regardless of JD (see exportResumeDocx.js).
    const activeTexts = (application.tailoredBullets || [])
      .filter((bullet) => !bullet.rejected)
      .map((bullet) => bullet.finalText);
    const effectiveSkills = application.tailoredSkills ?? resume?.skills ?? [];
    const sourceTexts = [
      ...activeTexts,
      application.tailoredSummary?.finalText,
      ...originalProjects.map((project) => project.description),
    ];
    const { aliases: idSkillAliases, matchers: idSkillMatchers } = await getSkillDictionaryForUser(req.user.id);
    const { verifiedSkills, skillMatchTypes } = computeVerifiedSkills(effectiveSkills, sourceTexts, idSkillMatchers, idSkillAliases);
    const titleSeniorityWarning = computeTitleSeniorityWarning(application.tailoredTitle);

    // Deliberately false whenever masterResumeSnapshotAt itself is missing
    // (every application created before this field existed) — otherwise
    // every pre-existing application would show "changed" as noise, not
    // signal, the first time this ships.
    const masterResumeChanged = Boolean(
      application.masterResumeSnapshotAt &&
        resume?.updatedAt &&
        resume.updatedAt > application.masterResumeSnapshotAt
    );

    return res.json({
      application,
      originalBullets: state.resumeBullets || [],
      originalSummary: state.resumeSummary || '',
      originalProjects,
      originalEducation,
      originalCertifications,
      originalVolunteerWork,
      masterResumeChanged,
      verificationResult: state.verificationResult || null,
      roleFitReason: application.status === 'role_mismatch' ? state.roleFit?.reason : undefined,
      verifiedSkills,
      skillMatchTypes,
      titleSeniorityWarning,
    });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to load application.' });
  }
});

// Single-application delete (distinct from resumes.js's whole-resume cascade
// in section 2.4) — see workflow doc section 2.5. Deletes the application
// document, its checkpoint/thread, and its GenerationCache entries. Not
// gated by status; the only UI entry point (Applications.jsx) happens to
// only ever show approved rows, but this route itself is general.
router.delete('/:id', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    await Application.deleteOne({ _id: id });
    const checkpointer = getCheckpointer();
    await checkpointer.deleteThread(id);
    await GenerationCache.deleteMany({ applicationId: id });

    return res.json({ deleted: true });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to delete application.' });
  }
});

// On-demand exports (replaces node 11's automatic tracker.xlsx/docx side
// effects) — generated fresh from Mongo each time, never stored as files.
// Nothing here is exportable until approved, per the "nothing is used
// before I approve it" principle enforced elsewhere in this app.
router.get('/:id/export/resume.docx', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status !== 'approved') {
      return res.status(400).json({ error: 'This application has not been approved yet.' });
    }

    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id });
    const graph = getJobAgentGraph();
    const snapshot = await graph.getState({ configurable: { thread_id: id } });
    const originalBullets = snapshot.values?.resumeBullets || [];
    const originalBulletsById = new Map(originalBullets.map((bullet) => [bullet.bulletId, bullet]));

    const buffer = await buildResumeDocxBuffer({
      personalInfo: resume?.personalInfo || {},
      tailoredSummary: application.tailoredSummary,
      tailoredTitle: application.tailoredTitle,
      tailoredBullets: application.tailoredBullets.filter((bullet) => !bullet.rejected),
      originalBulletsById,
      // Frozen-at-creation snapshot, falling back to a live read only for an
      // application from before these fields existed — see jobAgentGraph.js.
      education: snapshot.values?.resumeEducation ?? resume?.education ?? [],
      projects: snapshot.values?.resumeProjects ?? resume?.projects ?? [],
      certifications: snapshot.values?.resumeCertifications ?? resume?.certifications ?? [],
      volunteerWork: snapshot.values?.resumeVolunteerWork ?? resume?.volunteerWork ?? [],
      skills: application.tailoredSkills ?? resume?.skills ?? [],
    });

    const filename = buildExportFilename({
      fullName: resume?.personalInfo?.fullName,
      companyName: application.companyName,
      suffix: 'Resume',
    });
    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}"`,
    });
    return res.send(buffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate resume.' });
  }
});

// Same gating and content as GET /:id/export/resume.docx — builds the exact
// same .docx buffer, then converts it to PDF via LibreOffice headless (the
// same tool this project's own tooling already uses for rendering/
// verification). The intermediate .docx and the converted .pdf are both
// written to, and removed from, a temp directory inside
// convertDocxBufferToPdf — nothing is left on disk once the request
// completes, matching the "never stored server-side" rule.
router.get('/:id/export/resume.pdf', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status !== 'approved') {
      return res.status(400).json({ error: 'This application has not been approved yet.' });
    }

    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id });
    const graph = getJobAgentGraph();
    const snapshot = await graph.getState({ configurable: { thread_id: id } });
    const originalBullets = snapshot.values?.resumeBullets || [];
    const originalBulletsById = new Map(originalBullets.map((bullet) => [bullet.bulletId, bullet]));

    const docxBuffer = await buildResumeDocxBuffer({
      personalInfo: resume?.personalInfo || {},
      tailoredSummary: application.tailoredSummary,
      tailoredTitle: application.tailoredTitle,
      tailoredBullets: application.tailoredBullets.filter((bullet) => !bullet.rejected),
      originalBulletsById,
      // Frozen-at-creation snapshot, falling back to a live read only for an
      // application from before these fields existed — see jobAgentGraph.js.
      education: snapshot.values?.resumeEducation ?? resume?.education ?? [],
      projects: snapshot.values?.resumeProjects ?? resume?.projects ?? [],
      certifications: snapshot.values?.resumeCertifications ?? resume?.certifications ?? [],
      volunteerWork: snapshot.values?.resumeVolunteerWork ?? resume?.volunteerWork ?? [],
      skills: application.tailoredSkills ?? resume?.skills ?? [],
    });

    let pdfBuffer;
    try {
      pdfBuffer = await convertDocxBufferToPdf(docxBuffer);
    } catch (err) {
      console.error(err);
      return res.status(500).json({ error: 'Failed to convert resume to PDF.' });
    }

    const filename = buildExportFilename({
      fullName: resume?.personalInfo?.fullName,
      companyName: application.companyName,
      suffix: 'Resume',
      extension: 'pdf',
    });
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
    });
    return res.send(pdfBuffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate resume PDF.' });
  }
});

router.get('/:id/export/cover-letter.docx', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status !== 'approved') {
      return res.status(400).json({ error: 'This application has not been approved yet.' });
    }
    if (!application.coverLetterRequested) {
      return res.status(400).json({ error: 'No cover letter was requested for this application.' });
    }

    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id });
    const buffer = await buildCoverLetterDocxBuffer({
      personalInfo: resume?.personalInfo || {},
      companyName: application.companyName,
      coverLetterText: application.coverLetterText,
    });

    const filename = buildExportFilename({
      fullName: resume?.personalInfo?.fullName,
      companyName: application.companyName,
      suffix: 'CoverLetter',
    });
    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${filename}"`,
    });
    return res.send(buffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate cover letter.' });
  }
});

// Same gating/content as GET /:id/export/cover-letter.docx, converted to PDF
// via LibreOffice headless — see the comment on GET /:id/export/resume.pdf
// for the shared conversion/cleanup behavior.
router.get('/:id/export/cover-letter.pdf', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status !== 'approved') {
      return res.status(400).json({ error: 'This application has not been approved yet.' });
    }
    if (!application.coverLetterRequested) {
      return res.status(400).json({ error: 'No cover letter was requested for this application.' });
    }

    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id });
    const docxBuffer = await buildCoverLetterDocxBuffer({
      personalInfo: resume?.personalInfo || {},
      companyName: application.companyName,
      coverLetterText: application.coverLetterText,
    });

    let pdfBuffer;
    try {
      pdfBuffer = await convertDocxBufferToPdf(docxBuffer);
    } catch (err) {
      console.error(err);
      return res.status(500).json({ error: 'Failed to convert cover letter to PDF.' });
    }

    const filename = buildExportFilename({
      fullName: resume?.personalInfo?.fullName,
      companyName: application.companyName,
      suffix: 'CoverLetter',
      extension: 'pdf',
    });
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
    });
    return res.send(pdfBuffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate cover letter PDF.' });
  }
});

// Read-only diagnostic, not gated on status === 'approved' and never writes
// to the application document — purely informational, same non-blocking
// spirit as re-check (see key-decisions-log.md). Builds the exact same docx
// buffer GET /:id/export/resume.docx builds, then runs the same structural
// assertions exportResumeDocx.test.js already checks against it (contact
// info actually present in the extracted body text, not stuck in a header/
// footer part; no header/footer parts at all) plus a check that every
// section heading the current resume data should produce (SUMMARY and WORK
// HISTORY always; EDUCATION/PROJECTS/SKILLS only when that section has data)
// is actually present — for display as a checklist, not a test pass/fail.
router.get('/:id/searchability-check', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id });
    const graph = getJobAgentGraph();
    const snapshot = await graph.getState({ configurable: { thread_id: id } });
    const originalBullets = snapshot.values?.resumeBullets || [];
    const originalBulletsById = new Map(originalBullets.map((bullet) => [bullet.bulletId, bullet]));

    const personalInfo = resume?.personalInfo || {};
    // Frozen-at-creation snapshot, falling back to a live read only for an
    // application from before these fields existed — see jobAgentGraph.js.
    // Kept in sync with the actual export routes so this check can never
    // silently drift from what a real export would contain.
    const education = snapshot.values?.resumeEducation ?? resume?.education ?? [];
    const projects = snapshot.values?.resumeProjects ?? resume?.projects ?? [];
    const certifications = snapshot.values?.resumeCertifications ?? resume?.certifications ?? [];
    const volunteerWork = snapshot.values?.resumeVolunteerWork ?? resume?.volunteerWork ?? [];
    const skills = application.tailoredSkills ?? resume?.skills ?? [];

    const buffer = await buildResumeDocxBuffer({
      personalInfo,
      tailoredSummary: application.tailoredSummary,
      tailoredTitle: application.tailoredTitle,
      tailoredBullets: (application.tailoredBullets || []).filter((bullet) => !bullet.rejected),
      originalBulletsById,
      education,
      projects,
      certifications,
      volunteerWork,
      skills,
    });

    const { value: text } = await mammoth.extractRawText({ buffer });
    const zip = await JSZip.loadAsync(buffer);
    const hasHeaderOrFooterPart = Object.keys(zip.files).some((name) => /^word\/(header|footer)\d*\.xml$/i.test(name));

    const contactFields = [personalInfo.phone, personalInfo.email].filter(Boolean);
    const contactInfoPresent = contactFields.length > 0 && contactFields.every((value) => text.includes(value));

    const expectedHeadings = [
      'SUMMARY',
      'EXPERIENCE',
      ...(education.length > 0 ? ['EDUCATION'] : []),
      ...(certifications.length > 0 ? ['CERTIFICATIONS'] : []),
      ...(projects.length > 0 ? ['PROJECTS'] : []),
      ...(volunteerWork.length > 0 ? ['VOLUNTEER WORK'] : []),
      ...(skills.length > 0 ? ['SKILLS'] : []),
    ];
    const standardHeadingsPresent = expectedHeadings.every((heading) => text.includes(heading));

    return res.json({
      checks: [
        { id: 'contactInfoPresent', label: 'Contact info appears in the exported text', passed: contactInfoPresent },
        { id: 'noHeaderFooterElements', label: 'No header/footer elements used', passed: !hasHeaderOrFooterPart },
        { id: 'standardHeadingsPresent', label: 'Standard section headings present', passed: standardHeadingsPresent },
      ],
    });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to run the searchability check.' });
  }
});

// Read-only diagnostic, not gated on status === 'approved' and never writes
// to the application document — same non-blocking spirit as re-check and
// the searchability check above. Counts, per JD-requested canonical skill,
// how many times it (or any of its known aliases) appears in the JD text
// versus the current tailored resume — informational only, never feeds
// keywordGaps/atsScore/atsFlags or the retry conditional. Uses the current
// tailored, non-rejected bullet text (bullet.finalText) rather than the
// pre-tailoring graph-state bullets, so the counts match what's actually on
// screen/exported right now, including any human edits or excludes.
router.get('/:id/skill-frequency', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    const resumeBulletsForCounting = (application.tailoredBullets || [])
      .filter((bullet) => !bullet.rejected)
      .map((bullet) => ({ text: bullet.finalText }));

    const { aliases: freqSkillAliases, matchers: freqSkillMatchers } = await getSkillDictionaryForUser(req.user.id);
    const skillFrequency = computeSkillFrequency(
      application.jdSnapshot,
      resumeBulletsForCounting,
      application.jdCanonicalSkills,
      freqSkillMatchers,
      freqSkillAliases
    );

    return res.json({ skillFrequency });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to compute skill frequency.' });
  }
});

router.get('/export/tracker.xlsx', async (req, res) => {
  try {
    const applications = await Application.find({ userId: req.user.id, status: 'approved' }).sort({ approvedAt: -1 });
    const buffer = await buildTrackerXlsxBuffer(applications);

    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': 'attachment; filename="tracker.xlsx"',
    });
    return res.send(buffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate tracker spreadsheet.' });
  }
});

// Hand-edit one tailored bullet — direct Mongo write, no graph interaction.
router.patch('/:id/bullets/:bulletId', async (req, res) => {
  const { id, bulletId } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { text, rejected } = req.body;
  const hasText = text !== undefined;
  const hasRejected = rejected !== undefined;
  if (!hasText && !hasRejected) {
    return res.status(400).json({ error: 'text or rejected is required.' });
  }
  if (hasText && (typeof text !== 'string' || !text.trim())) {
    return res.status(400).json({ error: 'text is required.' });
  }
  if (hasRejected && typeof rejected !== 'boolean') {
    return res.status(400).json({ error: 'rejected must be a boolean.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    const bullet = application.tailoredBullets.find((b) => b.bulletId === bulletId);
    if (!bullet) {
      return res.status(404).json({ error: 'Tailored bullet not found.' });
    }

    if (hasText) {
      bullet.humanEditedText = text;
      bullet.finalText = text;
      bullet.editSource = 'human';
    }
    // Human override of node 5's keep/reject call — independent of text edits,
    // so it can re-include a bullet the model judged out of context (its text
    // is already the verbatim source, per tailorContent.js, so no fabrication
    // risk) or exclude one the model kept. Tagging it rejectionSource: 'human'
    // (as opposed to node 5's own default 'ai') is what lets this decision
    // survive a later retry instead of being silently overridden — see
    // mergeHumanEditedBullets/ensureRequiredBulletIncluded/
    // ensureEveryEmployerRepresented in jobAgentGraph.js.
    if (hasRejected) {
      bullet.rejected = rejected;
      bullet.rejectionSource = 'human';
    }
    await application.save();

    const activeTexts = application.tailoredBullets
      .filter((b) => !b.rejected)
      .map((b) => b.finalText);
    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id }).select('skills projects');
    const effectiveSkills = application.tailoredSkills ?? resume?.skills ?? [];
    const sourceTexts = [
      ...activeTexts,
      application.tailoredSummary?.finalText,
      ...(resume?.projects || []).map((project) => project.description),
    ];
    const { aliases: bulletSkillAliases, matchers: bulletSkillMatchers } = await getSkillDictionaryForUser(req.user.id);
    const { verifiedSkills, skillMatchTypes } = computeVerifiedSkills(effectiveSkills, sourceTexts, bulletSkillMatchers, bulletSkillAliases);

    return res.json({ application, verifiedSkills, skillMatchTypes });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to update tailored bullet.' });
  }
});

// Hand-edit the tailored summary — direct Mongo write, no graph interaction.
router.patch('/:id/summary', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { text } = req.body;
  if (typeof text !== 'string' || !text.trim()) {
    return res.status(400).json({ error: 'text is required.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (!application.tailoredSummary) {
      return res.status(400).json({ error: 'This application has no tailored summary to edit.' });
    }

    application.tailoredSummary.humanEditedText = text;
    application.tailoredSummary.finalText = text;
    application.tailoredSummary.editSource = 'human';
    await application.save();

    return res.json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to update tailored summary.' });
  }
});

// Hand-edit the tailored title — direct Mongo write, no graph interaction.
// Same shape as the summary edit route above.
router.patch('/:id/title', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { text } = req.body;
  if (typeof text !== 'string' || !text.trim()) {
    return res.status(400).json({ error: 'text is required.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (!application.tailoredTitle) {
      return res.status(400).json({ error: 'This application has no tailored title to edit.' });
    }

    application.tailoredTitle.humanEditedText = text;
    application.tailoredTitle.finalText = text;
    application.tailoredTitle.editSource = 'human';
    await application.save();

    const titleSeniorityWarning = computeTitleSeniorityWarning(application.tailoredTitle);

    return res.json({ application, titleSeniorityWarning });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to update tailored title.' });
  }
});

// Per-application override of the resume's skills list — display only, never
// touches gap analysis or ATS scoring (see server/src/services/verifiedSkills.js).
// Direct Mongo write, no graph interaction, same shape as the summary/bullet
// edit routes above.
router.patch('/:id/skills', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { skills } = req.body;
  if (!Array.isArray(skills)) {
    return res.status(400).json({ error: 'skills must be an array.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    application.tailoredSkills = skills;
    await application.save();

    const activeTexts = application.tailoredBullets
      .filter((bullet) => !bullet.rejected)
      .map((bullet) => bullet.finalText);
    const resume = await MasterResume.findOne({ _id: application.masterResumeId, userId: req.user.id }).select('projects');
    const sourceTexts = [
      ...activeTexts,
      application.tailoredSummary?.finalText,
      ...(resume?.projects || []).map((project) => project.description),
    ];
    const { aliases: skillsSkillAliases, matchers: skillsSkillMatchers } = await getSkillDictionaryForUser(req.user.id);
    const { verifiedSkills, skillMatchTypes } = computeVerifiedSkills(skills, sourceTexts, skillsSkillMatchers, skillsSkillAliases);

    return res.json({ application, verifiedSkills, skillMatchTypes });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to update skills.' });
  }
});

// Section 4a — re-check. Non-blocking, informational, no graph resume: runs
// node 6 AND node 9 against the current (possibly hand-edited) content,
// populating humanRecheckAtsScore/Flags alongside (never overwriting)
// atsScore/atsFlags from the original AI pass.
router.post('/:id/recheck', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status === 'role_mismatch') {
      return res.status(400).json({ error: 'No tailored content to re-check for a role-mismatch application.' });
    }

    const result = await computeHumanRecheck(application);
    Object.assign(application, result);
    await application.save();

    return res.json(result);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to re-check application.' });
  }
});

// The endpoint that actually resumes the paused graph. action: 'approve'
// merges the current (possibly hand-edited) content and ends the run;
// action: 'retry' sends it back through tailorContent -> deterministicVerification
// -> (coverLetterGeneration) -> styleLinting -> atsScoreAndRecruiter -> humanApproval
// with the given notes, pausing again (possibly after further automatic
// retries within that same pass, capped at 3 — see shouldRetryAutomatically).
// action: 'override' is only valid on a role_mismatch application — the human
// disagrees with node 4's gate and sends it straight to tailorContent,
// bypassing the gate entirely rather than re-running it (which would very
// likely reproduce the same verdict). This is the one place in the pipeline
// that previously had no recourse once the gate fired — every other decision
// point already lets the human have the final say.
router.post('/:id/resume', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { action, notes } = req.body;
  if (action !== 'approve' && action !== 'retry' && action !== 'override') {
    return res.status(400).json({ error: "action must be 'approve', 'retry', or 'override'." });
  }
  if (action === 'retry' && (typeof notes !== 'string' || !notes.trim())) {
    return res.status(400).json({ error: 'notes is required for a retry.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (action === 'override') {
      if (application.status !== 'role_mismatch') {
        return res.status(400).json({ error: 'override is only valid for a role-mismatch application.' });
      }
    } else {
      if (application.status === 'role_mismatch') {
        return res.status(400).json({ error: 'This application was a role mismatch — there is nothing to approve or retry.' });
      }
      if (application.status === 'approved') {
        return res.status(400).json({ error: 'This application has already been approved.' });
      }
      if (action === 'retry' && (application.retryCount ?? 0) >= MAX_RETRY_COUNT) {
        return res.status(400).json({ error: `This application has already used all ${MAX_RETRY_COUNT} retries.` });
      }
    }

    const resumePayload =
      action === 'approve'
        ? {
            action: 'approve',
            tailoredBullets: application.tailoredBullets,
            tailoredSummary: application.tailoredSummary,
            tailoredTitle: application.tailoredTitle,
          }
        : action === 'retry'
          ? {
              action: 'retry',
              notes,
              tailoredBullets: application.tailoredBullets,
              tailoredSummary: application.tailoredSummary,
              tailoredTitle: application.tailoredTitle,
            }
          : { action: 'override' };

    const snapshot = await resumeGraph(id, resumePayload);
    const state = snapshot.values;

    if (action === 'approve') {
      application.status = 'approved';
      application.approvedAt = new Date();
      application.tailoredBullets = state.tailoredBullets;
      application.tailoredSummary = state.tailoredSummary;
      application.tailoredTitle = state.tailoredTitle;
      application.coverLetterText = state.coverLetterText;
      application.atsScore = state.atsScore;
      application.atsFlags = state.atsFlags;
      application.recruiterFeedback = state.recruiterFeedback;
      application.retryCount = state.retryCount ?? application.retryCount;
    } else if (action === 'retry') {
      application.status = 'pending_approval';
      application.retryNotes.push({ notes });
      application.tailoredBullets = state.tailoredBullets;
      application.tailoredSummary = state.tailoredSummary;
      application.tailoredTitle = state.tailoredTitle;
      application.keywordGaps = state.keywordGaps;
      application.coverLetterText = state.coverLetterText;
      application.atsScore = state.atsScore;
      application.atsFlags = state.atsFlags;
      application.recruiterFeedback = state.recruiterFeedback;
      application.retryCount = state.retryCount;

      // Refresh the human-recheck panel against this round's fresh content —
      // otherwise it keeps showing whatever it said before this retry, which
      // reads as "nothing changed" even though the tailored content did.
      const recheckResult = await computeHumanRecheck(application);
      Object.assign(application, recheckResult);
    } else {
      // override — first time this application ever runs tailorContent, so
      // this mirrors POST /'s own "plausible" branch, not the retry branch.
      application.status = 'pending_approval';
      application.retryNotes.push({ notes: 'Role-fit gate manually overridden by user — proceeded to tailoring.' });
      application.tailoredBullets = state.tailoredBullets;
      application.tailoredSummary = state.tailoredSummary;
      application.tailoredTitle = state.tailoredTitle;
      application.keywordGaps = state.keywordGaps;
      application.coverLetterText = state.coverLetterText;
      application.atsScore = state.atsScore;
      application.atsFlags = state.atsFlags;
      application.recruiterFeedback = state.recruiterFeedback;
      application.retryCount = state.retryCount ?? 0;

      const recheckResult = await computeHumanRecheck(application);
      Object.assign(application, recheckResult);
    }

    await application.save();

    return res.json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to resume application.' });
  }
});

// Section 4a — suggest missing skills. Never inserts text directly into the
// tailored output: goes through the same tagBullet flow as a normal upload,
// then retries with it in the pool. saveToMasterResume (default true) decides
// where it lives:
//   true  — a real resumeBullets document, same as today: permanent, shared
//           with every other application against this master resume.
//   false — scoped to just this application. Never written to resumeBullets
//           at all, so no other application, gap-analysis run, or the Master
//           Resume bullets page ever sees it — it only exists inside this
//           application's own graph state, and disappears automatically
//           if/when this application is deleted (its checkpoint thread is
//           deleted too, and that's the only place this bullet ever lived).
router.post('/:id/suggest-skills/accept', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { skill, bulletText, role, company, dateRange, saveToMasterResume = true } = req.body;
  if (typeof skill !== 'string' || !skill.trim()) {
    return res.status(400).json({ error: 'skill is required.' });
  }
  if (typeof bulletText !== 'string' || !bulletText.trim()) {
    return res.status(400).json({ error: 'bulletText is required.' });
  }
  if (typeof saveToMasterResume !== 'boolean') {
    return res.status(400).json({ error: 'saveToMasterResume must be a boolean.' });
  }

  try {
    const application = await Application.findOne({ _id: id, userId: req.user.id });
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status === 'role_mismatch' || application.status === 'approved') {
      return res.status(400).json({ error: 'Cannot suggest a skill for this application.' });
    }
    if ((application.retryCount ?? 0) >= MAX_RETRY_COUNT) {
      return res.status(400).json({ error: `This application has already used all ${MAX_RETRY_COUNT} retries.` });
    }
    if (!(application.keywordGaps || []).includes(skill)) {
      return res.status(400).json({ error: "skill is not one of this application's keyword gaps." });
    }

    const { skills, metrics } = await tagBullet(bulletText);
    const { aliases: suggestSkillAliases } = await getSkillDictionaryForUser(req.user.id);
    const canonicalSkills = skills.map((s) => canonicalizeSkill(s, suggestSkillAliases));
    const trimmedRole = typeof role === 'string' && role.trim() ? role.trim() : undefined;
    const trimmedCompany = typeof company === 'string' && company.trim() ? company.trim() : undefined;
    const trimmedDateRange = typeof dateRange === 'string' && dateRange.trim() ? dateRange.trim() : undefined;

    const masterBullets = await ResumeBullet.find({ masterResumeId: application.masterResumeId }).sort({ order: 1 });

    let newBullet;
    let resumeBulletsForGraph;
    let requiredBulletId;

    if (saveToMasterResume) {
      // Appends after everything already on the master resume — see the
      // `order` field's own comment on ResumeBullet.js.
      const nextOrder = (masterBullets[masterBullets.length - 1]?.order ?? -1) + 1;
      newBullet = await ResumeBullet.create({
        masterResumeId: application.masterResumeId,
        text: bulletText,
        order: nextOrder,
        skills,
        canonicalSkills,
        metrics,
        role: trimmedRole,
        company: trimmedCompany,
        dateRange: trimmedDateRange,
      });
      resumeBulletsForGraph = buildResumeBulletsForGraph([...masterBullets, newBullet]);
      requiredBulletId = newBullet._id.toString();
    } else {
      // A bullet privately added earlier in THIS application lives only in
      // this thread's own state, never in resumeBullets — so a fresh Mongo
      // read alone would silently drop it. Carry forward anything already in
      // the current candidate pool that isn't one of the real master bullets.
      const masterBulletIds = new Set(masterBullets.map((bullet) => bullet._id.toString()));
      const graph = getJobAgentGraph();
      const currentSnapshot = await graph.getState({ configurable: { thread_id: id } });
      const existingPrivateBullets = (currentSnapshot.values?.resumeBullets || []).filter(
        (bullet) => !masterBulletIds.has(bullet.bulletId)
      );

      newBullet = {
        bulletId: randomUUID(),
        text: bulletText,
        skills,
        canonicalSkills,
        metrics,
        role: trimmedRole,
        company: trimmedCompany,
        dateRange: trimmedDateRange,
      };
      resumeBulletsForGraph = [
        ...buildResumeBulletsForGraph(masterBullets),
        ...existingPrivateBullets,
        {
          bulletId: newBullet.bulletId,
          text: newBullet.text,
          role: newBullet.role,
          company: newBullet.company,
          dateRange: newBullet.dateRange,
          canonicalSkills: newBullet.canonicalSkills,
        },
      ];
      requiredBulletId = newBullet.bulletId;
    }

    const notes =
      `New skill added to resume: "${skill}". New bullet: "${bulletText}". ` +
      'Consider incorporating this bullet into the tailored content if relevant.';

    const snapshot = await resumeGraph(id, {
      action: 'retry',
      notes,
      tailoredBullets: application.tailoredBullets,
      tailoredSummary: application.tailoredSummary,
      tailoredTitle: application.tailoredTitle,
      resumeBullets: resumeBulletsForGraph,
      requiredBulletId,
    });
    const state = snapshot.values;

    application.status = 'pending_approval';
    application.retryNotes.push({ notes });
    application.tailoredBullets = state.tailoredBullets;
    application.tailoredSummary = state.tailoredSummary;
    application.tailoredTitle = state.tailoredTitle;
    application.keywordGaps = state.keywordGaps;
    application.coverLetterText = state.coverLetterText;
    application.atsScore = state.atsScore;
    application.atsFlags = state.atsFlags;
    application.recruiterFeedback = state.recruiterFeedback;
    application.retryCount = state.retryCount;
    await application.save();

    return res.json({ application, newBullet, scope: saveToMasterResume ? 'master' : 'application' });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to add suggested skill.' });
  }
});

export default router;
