import { Router } from 'express';
import mongoose from 'mongoose';
import { createHash } from 'node:crypto';
import { Command } from '@langchain/langgraph';
import Application from '../models/Application.js';
import MasterResume from '../models/MasterResume.js';
import ResumeBullet from '../models/ResumeBullet.js';
import { normalizeSkills } from '../services/normalizeSkills.js';
import { canonicalizeSkill } from '../services/canonicalizeSkill.js';
import { tagBullet } from '../services/tagBullet.js';
import { verifyBullet, verifySummary, trustHumanEdit } from '../services/deterministicVerification.js';
import { gapAnalysis } from '../services/gapAnalysis.js';
import { atsScoreAndRecruiter } from '../services/atsScoreAndRecruiter.js';
import { buildResumeDocxBuffer } from '../services/exportResumeDocx.js';
import { buildCoverLetterDocxBuffer } from '../services/exportCoverLetterDocx.js';
import { buildTrackerXlsxBuffer } from '../services/exportTrackerXlsx.js';
import { getJobAgentGraph, getCheckpointer } from '../graph/graphInstance.js';
import GenerationCache from '../models/GenerationCache.js';

const router = Router();

function buildResumeBulletsForGraph(bullets) {
  return bullets.map((bullet) => ({
    bulletId: bullet._id.toString(),
    text: bullet.text,
    role: bullet.role,
    company: bullet.company,
    dateRange: bullet.dateRange,
    canonicalSkills: bullet.canonicalSkills,
  }));
}

function sanitizeFilename(name) {
  return (name || 'application').replace(/[^a-z0-9 _-]/gi, '').trim() || 'application';
}

// Resumes the one interrupt() in node 10 with a Command, then reads back the
// resulting checkpoint — the only place this route file touches the graph.
async function resumeGraph(applicationId, resumePayload) {
  const graph = getJobAgentGraph();
  await graph.invoke(new Command({ resume: resumePayload }), { configurable: { thread_id: applicationId } });
  return graph.getState({ configurable: { thread_id: applicationId } });
}

// Section 4a — re-check computation. Runs node 6 AND node 9 against an
// application's CURRENT tailoredBullets/tailoredSummary (possibly hand-edited,
// or freshly regenerated by a retry), without saving. Shared by the standalone
// POST /:id/recheck route and by the retry branch of POST /:id/resume, so the
// human-recheck panel reflects a fresh retry immediately instead of only
// updating on the next manual "Re-check edited text" click.
async function computeHumanRecheck(application) {
  const graph = getJobAgentGraph();
  const snapshot = await graph.getState({ configurable: { thread_id: application._id.toString() } });
  const { resumeBullets = [], matchedSkills = [], yearsOfExperience } = snapshot.values || {};
  const bulletsById = new Map(resumeBullets.map((bullet) => [bullet.bulletId, bullet]));

  const bulletResults = application.tailoredBullets.map((tailoredBullet) => {
    const sourceBullet = bulletsById.get(tailoredBullet.sourceBulletId);
    const result =
      tailoredBullet.editSource === 'human'
        ? trustHumanEdit(tailoredBullet.finalText)
        : verifyBullet({ generatedText: tailoredBullet.finalText, sourceBullet });
    return { bulletId: tailoredBullet.bulletId, rejected: tailoredBullet.rejected, ...result };
  });
  const bulletFlags = bulletResults.flatMap((result) => [
    ...result.fabricatedSkills.map((skill) => `bullet ${result.bulletId}: fabricated skill "${skill}"`),
    ...result.fabricatedMetrics.map((metric) => `bullet ${result.bulletId}: fabricated metric "${metric}"`),
  ]);

  const selectedBullets = application.tailoredBullets
    .filter((tailoredBullet) => !tailoredBullet.rejected)
    .map((tailoredBullet) => bulletsById.get(tailoredBullet.sourceBulletId));
  const summaryResult = !application.tailoredSummary
    ? { passed: true, fabricatedSkills: [], fabricatedMetrics: [], claimedSkills: [] }
    : application.tailoredSummary.editSource === 'human'
      ? trustHumanEdit(application.tailoredSummary.finalText)
      : verifySummary({
          generatedText: application.tailoredSummary.finalText,
          matchedSkills,
          selectedBullets,
          yearsOfExperience,
        });

  const summaryFlags = [
    ...summaryResult.fabricatedSkills.map((skill) => `summary: fabricated skill "${skill}"`),
    ...summaryResult.fabricatedMetrics.map((metric) => `summary: fabricated metric "${metric}"`),
  ];

  const overallPassed = bulletResults.every((result) => result.passed) && summaryResult.passed;

  // A live, application-scoped view of what's still missing — credits any
  // skill the current tailored content actually claims and gets to keep
  // (verified AI claims + trusted human claims), on top of the master
  // resume's own coverage. Never overwrites the original keywordGaps, which
  // stays tied purely to the master resume.
  const resumeCanonicalSkills = [...new Set(resumeBullets.flatMap((bullet) => bullet.canonicalSkills || []))];
  const verifiedBulletSkills = bulletResults
    .filter((result) => !result.rejected)
    .flatMap((result) => result.claimedSkills.filter((skill) => !result.fabricatedSkills.includes(skill)));
  const verifiedSummarySkills = summaryResult.claimedSkills.filter((skill) => !summaryResult.fabricatedSkills.includes(skill));
  const effectiveSkills = [...new Set([...resumeCanonicalSkills, ...verifiedBulletSkills, ...verifiedSummarySkills])];
  const humanRecheckKeywordGaps = gapAnalysis(application.jdCanonicalSkills, effectiveSkills);

  const atsResult = await atsScoreAndRecruiter({
    jdText: application.jdSnapshot,
    tailoredBullets: application.tailoredBullets.filter((bullet) => !bullet.rejected),
    tailoredSummary: application.tailoredSummary,
    coverLetterText: application.coverLetterText,
    keywordGaps: humanRecheckKeywordGaps,
    verificationResult: { bullets: bulletResults, summary: summaryResult, overallPassed },
    applicationId: application._id.toString(),
    resumeVersion: application.masterResumeId,
  });

  return {
    humanRecheckAtsScore: atsResult.atsScore,
    humanRecheckAtsFlags: [...bulletFlags, ...summaryFlags, ...atsResult.atsFlags.map((flag) => `ats: ${flag}`)],
    humanRecheckRecruiterFeedback: atsResult.recruiterFeedback,
    humanRecheckKeywordGaps,
  };
}

// For the Applications list page — approved applications only.
router.get('/', async (req, res) => {
  try {
    const applications = await Application.find({ status: 'approved' }).sort({ approvedAt: -1 });
    return res.json({ applications });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to list applications.' });
  }
});

// Section 3 — create + start.
router.post('/', async (req, res) => {
  const { masterResumeId, jdText, companyName, jobTitle, referenceUrl, coverLetterRequested } = req.body;

  if (!mongoose.isValidObjectId(masterResumeId)) {
    return res.status(400).json({ error: 'Invalid masterResumeId.' });
  }
  if (typeof jdText !== 'string' || !jdText.trim()) {
    return res.status(400).json({ error: 'jdText is required.' });
  }
  if (typeof companyName !== 'string' || !companyName.trim()) {
    return res.status(400).json({ error: 'companyName is required.' });
  }
  if (typeof jobTitle !== 'string' || !jobTitle.trim()) {
    return res.status(400).json({ error: 'jobTitle is required.' });
  }

  try {
    const normalizedJdText = jdText.trim().replace(/\s+/g, ' ');
    const jdTextHash = createHash('sha256').update(normalizedJdText).digest('hex');

    const existing = await Application.findOne({ masterResumeId, jdTextHash });
    if (existing) {
      return res.json({ application: existing, deduped: true });
    }

    const resume = await MasterResume.findOne({ _id: masterResumeId, status: 'active' });
    if (!resume) {
      return res.status(404).json({ error: 'Resume not found.' });
    }

    const bullets = await ResumeBullet.find({ masterResumeId });
    if (bullets.length === 0) {
      return res.status(400).json({ error: 'Selected resume has no bullets.' });
    }

    const resumeCanonicalSkills = normalizeSkills(bullets.flatMap((bullet) => bullet.skills));
    const resumeBulletsForGraph = buildResumeBulletsForGraph(bullets);

    let application;
    try {
      application = await Application.create({
        masterResumeId,
        companyName: companyName.trim(),
        jobTitle: jobTitle.trim(),
        referenceUrl: (referenceUrl || '').trim(),
        jdSnapshot: jdText,
        jdTextHash,
        coverLetterRequested: Boolean(coverLetterRequested),
        status: 'in_progress',
      });
    } catch (err) {
      if (err.code === 11000) {
        const winner = await Application.findOne({ masterResumeId, jdTextHash });
        return res.json({ application: winner, deduped: true });
      }
      throw err;
    }

    const applicationId = application._id.toString();
    const graph = getJobAgentGraph();

    await graph.invoke(
      {
        applicationId,
        masterResumeId,
        companyName: companyName.trim(),
        jdText,
        resumeSummary: resume.summary,
        resumeTitle: resume.personalInfo?.title,
        resumeCanonicalSkills,
        resumeBullets: resumeBulletsForGraph,
        coverLetterRequested: Boolean(coverLetterRequested),
      },
      { configurable: { thread_id: applicationId } }
    );

    const snapshot = await graph.getState({ configurable: { thread_id: applicationId } });
    const state = snapshot.values;

    application.jdKeywords = state.jdKeywords;
    application.jdCanonicalSkills = state.jdCanonicalSkills;
    application.keywordGaps = state.keywordGaps;

    if (state.roleFit?.fit === 'low') {
      application.status = 'role_mismatch';
    } else {
      application.status = 'pending_approval';
      application.tailoredBullets = state.tailoredBullets;
      application.tailoredSummary = state.tailoredSummary;
      application.coverLetterText = state.coverLetterText;
      application.atsScore = state.atsScore;
      application.atsFlags = state.atsFlags;
      application.recruiterFeedback = state.recruiterFeedback;
      application.retryCount = state.retryCount ?? 0;
    }

    await application.save();

    return res.status(201).json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to create and start application.' });
  }
});

// For the Approval page — merges the Mongo doc with data section 8 doesn't
// persist (the original bullets, the verification result, the role-mismatch
// reason), sourced live from the checkpointer instead of duplicating it.
router.get('/:id', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    const graph = getJobAgentGraph();
    const snapshot = await graph.getState({ configurable: { thread_id: id } });
    const state = snapshot.values || {};

    return res.json({
      application,
      originalBullets: state.resumeBullets || [],
      originalSummary: state.resumeSummary || '',
      verificationResult: state.verificationResult || null,
      roleFitReason: application.status === 'role_mismatch' ? state.roleFit?.reason : undefined,
    });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to load application.' });
  }
});

// Single-application delete (distinct from resumes.js's whole-resume cascade
// in section 2.4) — see workflow doc section 2.5. Deletes the application
// document, its checkpoint/thread, and its GenerationCache entries. Not
// gated by status; the only UI entry point (Applications.jsx) happens to
// only ever show approved rows, but this route itself is general.
router.delete('/:id', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    await Application.deleteOne({ _id: id });
    const checkpointer = getCheckpointer();
    await checkpointer.deleteThread(id);
    await GenerationCache.deleteMany({ applicationId: id });

    return res.json({ deleted: true });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to delete application.' });
  }
});

// On-demand exports (replaces node 11's automatic tracker.xlsx/docx side
// effects) — generated fresh from Mongo each time, never stored as files.
// Nothing here is exportable until approved, per the "nothing is used
// before I approve it" principle enforced elsewhere in this app.
router.get('/:id/export/resume.docx', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status !== 'approved') {
      return res.status(400).json({ error: 'This application has not been approved yet.' });
    }

    const resume = await MasterResume.findById(application.masterResumeId);
    const graph = getJobAgentGraph();
    const snapshot = await graph.getState({ configurable: { thread_id: id } });
    const originalBullets = snapshot.values?.resumeBullets || [];
    const originalBulletsById = new Map(originalBullets.map((bullet) => [bullet.bulletId, bullet]));

    const buffer = await buildResumeDocxBuffer({
      personalInfo: resume?.personalInfo || {},
      tailoredSummary: application.tailoredSummary,
      tailoredBullets: application.tailoredBullets.filter((bullet) => !bullet.rejected),
      originalBulletsById,
      education: resume?.education || [],
      projects: resume?.projects || [],
      skills: resume?.skills || [],
    });

    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${sanitizeFilename(application.companyName)} - Resume.docx"`,
    });
    return res.send(buffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate resume.' });
  }
});

router.get('/:id/export/cover-letter.docx', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status !== 'approved') {
      return res.status(400).json({ error: 'This application has not been approved yet.' });
    }
    if (!application.coverLetterRequested) {
      return res.status(400).json({ error: 'No cover letter was requested for this application.' });
    }

    const resume = await MasterResume.findById(application.masterResumeId);
    const buffer = await buildCoverLetterDocxBuffer({
      personalInfo: resume?.personalInfo || {},
      companyName: application.companyName,
      coverLetterText: application.coverLetterText,
    });

    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${sanitizeFilename(application.companyName)} - Cover Letter.docx"`,
    });
    return res.send(buffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate cover letter.' });
  }
});

router.get('/export/tracker.xlsx', async (req, res) => {
  try {
    const applications = await Application.find({ status: 'approved' }).sort({ approvedAt: -1 });
    const buffer = await buildTrackerXlsxBuffer(applications);

    res.set({
      'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'Content-Disposition': 'attachment; filename="tracker.xlsx"',
    });
    return res.send(buffer);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to generate tracker spreadsheet.' });
  }
});

// Hand-edit one tailored bullet — direct Mongo write, no graph interaction.
router.patch('/:id/bullets/:bulletId', async (req, res) => {
  const { id, bulletId } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { text, rejected } = req.body;
  const hasText = text !== undefined;
  const hasRejected = rejected !== undefined;
  if (!hasText && !hasRejected) {
    return res.status(400).json({ error: 'text or rejected is required.' });
  }
  if (hasText && (typeof text !== 'string' || !text.trim())) {
    return res.status(400).json({ error: 'text is required.' });
  }
  if (hasRejected && typeof rejected !== 'boolean') {
    return res.status(400).json({ error: 'rejected must be a boolean.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }

    const bullet = application.tailoredBullets.find((b) => b.bulletId === bulletId);
    if (!bullet) {
      return res.status(404).json({ error: 'Tailored bullet not found.' });
    }

    if (hasText) {
      bullet.humanEditedText = text;
      bullet.finalText = text;
      bullet.editSource = 'human';
    }
    // Human override of node 5's keep/reject call — independent of text edits,
    // so it can re-include a bullet the model judged out of context (its text
    // is already the verbatim source, per tailorContent.js, so no fabrication
    // risk) or exclude one the model kept. Tagging it rejectionSource: 'human'
    // (as opposed to node 5's own default 'ai') is what lets this decision
    // survive a later retry instead of being silently overridden — see
    // mergeHumanEditedBullets/ensureRequiredBulletIncluded/
    // ensureEveryEmployerRepresented in jobAgentGraph.js.
    if (hasRejected) {
      bullet.rejected = rejected;
      bullet.rejectionSource = 'human';
    }
    await application.save();

    return res.json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to update tailored bullet.' });
  }
});

// Hand-edit the tailored summary — direct Mongo write, no graph interaction.
router.patch('/:id/summary', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { text } = req.body;
  if (typeof text !== 'string' || !text.trim()) {
    return res.status(400).json({ error: 'text is required.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (!application.tailoredSummary) {
      return res.status(400).json({ error: 'This application has no tailored summary to edit.' });
    }

    application.tailoredSummary.humanEditedText = text;
    application.tailoredSummary.finalText = text;
    application.tailoredSummary.editSource = 'human';
    await application.save();

    return res.json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to update tailored summary.' });
  }
});

// Section 4a — re-check. Non-blocking, informational, no graph resume: runs
// node 6 AND node 9 against the current (possibly hand-edited) content,
// populating humanRecheckAtsScore/Flags alongside (never overwriting)
// atsScore/atsFlags from the original AI pass.
router.post('/:id/recheck', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status === 'role_mismatch') {
      return res.status(400).json({ error: 'No tailored content to re-check for a role-mismatch application.' });
    }

    const result = await computeHumanRecheck(application);
    Object.assign(application, result);
    await application.save();

    return res.json(result);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to re-check application.' });
  }
});

// The endpoint that actually resumes the paused graph. action: 'approve'
// merges the current (possibly hand-edited) content and ends the run;
// action: 'retry' sends it back through tailorContent -> deterministicVerification
// -> (coverLetterGeneration) -> styleLinting -> atsScoreAndRecruiter -> humanApproval
// with the given notes, pausing again (possibly after further automatic
// retries within that same pass, capped at 3 — see shouldRetryAutomatically).
router.post('/:id/resume', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { action, notes } = req.body;
  if (action !== 'approve' && action !== 'retry') {
    return res.status(400).json({ error: "action must be 'approve' or 'retry'." });
  }
  if (action === 'retry' && (typeof notes !== 'string' || !notes.trim())) {
    return res.status(400).json({ error: 'notes is required for a retry.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status === 'role_mismatch') {
      return res.status(400).json({ error: 'This application was a role mismatch — there is nothing to approve or retry.' });
    }
    if (application.status === 'approved') {
      return res.status(400).json({ error: 'This application has already been approved.' });
    }

    const resumePayload =
      action === 'approve'
        ? { action: 'approve', tailoredBullets: application.tailoredBullets, tailoredSummary: application.tailoredSummary }
        : { action: 'retry', notes, tailoredBullets: application.tailoredBullets };

    const snapshot = await resumeGraph(id, resumePayload);
    const state = snapshot.values;

    if (action === 'approve') {
      application.status = 'approved';
      application.approvedAt = new Date();
      application.tailoredBullets = state.tailoredBullets;
      application.tailoredSummary = state.tailoredSummary;
      application.coverLetterText = state.coverLetterText;
      application.atsScore = state.atsScore;
      application.atsFlags = state.atsFlags;
      application.recruiterFeedback = state.recruiterFeedback;
      application.retryCount = state.retryCount ?? application.retryCount;
    } else {
      application.status = 'pending_approval';
      application.retryNotes.push({ notes });
      application.tailoredBullets = state.tailoredBullets;
      application.tailoredSummary = state.tailoredSummary;
      application.keywordGaps = state.keywordGaps;
      application.coverLetterText = state.coverLetterText;
      application.atsScore = state.atsScore;
      application.atsFlags = state.atsFlags;
      application.recruiterFeedback = state.recruiterFeedback;
      application.retryCount = state.retryCount;

      // Refresh the human-recheck panel against this round's fresh content —
      // otherwise it keeps showing whatever it said before this retry, which
      // reads as "nothing changed" even though the tailored content did.
      const recheckResult = await computeHumanRecheck(application);
      Object.assign(application, recheckResult);
    }

    await application.save();

    return res.json({ application });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to resume application.' });
  }
});

// Section 4a — suggest missing skills. Never inserts text directly into the
// tailored output: writes a real resumeBullets document through the same
// tagBullet flow as a normal upload, then retries with it in the pool.
router.post('/:id/suggest-skills/accept', async (req, res) => {
  const { id } = req.params;
  if (!mongoose.isValidObjectId(id)) {
    return res.status(400).json({ error: 'Invalid application id.' });
  }

  const { skill, bulletText, role, company, dateRange } = req.body;
  if (typeof skill !== 'string' || !skill.trim()) {
    return res.status(400).json({ error: 'skill is required.' });
  }
  if (typeof bulletText !== 'string' || !bulletText.trim()) {
    return res.status(400).json({ error: 'bulletText is required.' });
  }

  try {
    const application = await Application.findById(id);
    if (!application) {
      return res.status(404).json({ error: 'Application not found.' });
    }
    if (application.status === 'role_mismatch' || application.status === 'approved') {
      return res.status(400).json({ error: 'Cannot suggest a skill for this application.' });
    }
    if (!(application.keywordGaps || []).includes(skill)) {
      return res.status(400).json({ error: "skill is not one of this application's keyword gaps." });
    }

    const { skills, metrics } = await tagBullet(bulletText);
    const canonicalSkills = skills.map(canonicalizeSkill);
    const newBullet = await ResumeBullet.create({
      masterResumeId: application.masterResumeId,
      text: bulletText,
      skills,
      canonicalSkills,
      metrics,
      role: typeof role === 'string' && role.trim() ? role.trim() : undefined,
      company: typeof company === 'string' && company.trim() ? company.trim() : undefined,
      dateRange: typeof dateRange === 'string' && dateRange.trim() ? dateRange.trim() : undefined,
    });

    const allBullets = await ResumeBullet.find({ masterResumeId: application.masterResumeId });
    const resumeBulletsForGraph = buildResumeBulletsForGraph(allBullets);

    const notes =
      `New skill added to resume: "${skill}". New bullet: "${bulletText}". ` +
      'Consider incorporating this bullet into the tailored content if relevant.';

    const snapshot = await resumeGraph(id, {
      action: 'retry',
      notes,
      tailoredBullets: application.tailoredBullets,
      resumeBullets: resumeBulletsForGraph,
      requiredBulletId: newBullet._id.toString(),
    });
    const state = snapshot.values;

    application.status = 'pending_approval';
    application.retryNotes.push({ notes });
    application.tailoredBullets = state.tailoredBullets;
    application.tailoredSummary = state.tailoredSummary;
    application.keywordGaps = state.keywordGaps;
    application.coverLetterText = state.coverLetterText;
    application.atsScore = state.atsScore;
    application.atsFlags = state.atsFlags;
    application.recruiterFeedback = state.recruiterFeedback;
    application.retryCount = state.retryCount;
    await application.save();

    return res.json({ application, newBullet });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: 'Failed to add suggested skill.' });
  }
});

export default router;
